# Generated by Django 5.2.7 on 2026-04-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
