# Generated by Django 5.2.7 on 2026-04-17 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0007_alter_calllog_duration_alter_calllog_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='call_id',
            field=models.BigIntegerField(help_text='Must be a 10-digit integer.', validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
