# Generated by Django 5.2.7 on 2026-08-18 15:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatbot', '0019_calllogminuterollup'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_projects', to='Chatbot.client')),
            ],
            options={
                'ordering': ['client__client_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoutingFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.PositiveIntegerField(default=1, help_text='Relative distribution weight. For example, use 60 and 40 for a 60/40 split.', validators=[django.core.validators.MinValueValidator(1)])),
                ('active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='Chatbot.routingproject')),
            ],
            options={
                'ordering': ['project__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DialerRoutingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable only after the project flows, batches, and route IPs are configured.')),
                ('dialer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routing_policy', to='Chatbot.dialer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dialer_policies', to='Chatbot.routingproject')),
            ],
            options={
                'verbose_name_plural': 'Dialer routing policies',
                'ordering': ['dialer__dialer_name'],
            },
        ),
        migrations.CreateModel(
            name='RoutingEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_ip', models.CharField(max_length=255)),
                ('weight', models.PositiveIntegerField(default=1, help_text='Relative distribution weight. For example, use 60 and 40 for a 60/40 split.', validators=[django.core.validators.MinValueValidator(1)])),
                ('active', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='Chatbot.dialerroutingpolicy')),
            ],
            options={
                'ordering': ['policy__dialer__dialer_name', 'route_ip'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'route_ip'), name='routing_endpoint_policy_ip_unique')],
            },
        ),
        migrations.CreateModel(
            name='RoutingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('weight', models.PositiveIntegerField(default=1, help_text='Relative distribution weight within this flow.', validators=[django.core.validators.MinValueValidator(1)])),
                ('active', models.BooleanField(default=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='Chatbot.routingflow')),
            ],
            options={
                'ordering': ['flow__project__name', 'flow__name', 'value'],
                'constraints': [models.UniqueConstraint(fields=('flow', 'value'), name='routing_batch_flow_value_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='routingproject',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='routing_project_client_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='routingflow',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='routing_flow_project_name_unique'),
        ),
    ]
